sudo: true
language: nix
env:
  - NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/f52eaf4fb371112f7a5b28d71f97de71709002a0.tar.gz
cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/Enlambda/nix-channelstatus/.stack-work"

before_install:
- sudo mount -o remount,exec,size=4G,mode=755 /run/user || true
- pushd frontend
- nix-shell --run "npm i && elm package install -y" -j 8
- popd

script:
- nix-build
