sudo: true
language: nix
env:
  - NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/e18dac705ad36482880e23d0a89c60c3514cb446.tar.gz
cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/Enlambda/nix-channelstatus/.stack-work"

before_install:
- nix-shell -p stack --run "stack build --nix --only-dependencies --fast"

script:
- nix-shell -p stack --run "stack build --nix --test"
